name: example
description: A sample project using FlutterGen.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.9.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen:
    path: ../

flutter_gen:
  assets:
    outputs: lib/gen/
    # Auto inputs from flutter/assets.

  fonts:
    outputs: lib/gen/
    # Auto inputs from flutter/fonts.

  #  intl:
  #    outputs: lib/gen/
  #    intputs:
  #      - l10-arb/
  #      # or
  #      # - l10-arb/1ntl_messages_en.arb
  #      # - l10-arb/intl_messages_ja.arb

  colors:
    outputs: lib/gen/
    inputs:
      - color/colors.xml
      - color/colors2.xml
      - color/colors3.xml

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/chip/
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Italic.ttf
          style: italic
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
        - asset: fonts/RobotoMono-Bold.ttf
          weight: 700
