name: flutter_gen
description: The Flutter code generator for your assets, fonts, colors, localize, … — Get rid of all String-based APIs.
version: 0.0.8
homepage: https://github.com/wasabeef/FlutterGen

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  build: ^1.3.0
  source_gen: ^0.9.6
  path: 1.7.0
  yaml: ^2.2.1
  mime: ^0.9.7
  xml: ^4.2.0
  dart_style: ^1.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  test:
  build_test:
  pedantic:
