name: flutter_gen
description: A new Flutter package project.
version: 0.0.2
homepage: https://github.com/wasabeef/FlutterGen

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter
  build:
  source_gen:
  path:
  yaml:
  mime:

dev_dependencies:
  flutter_test:
    sdk: flutter