name: flutter_gen
description: The Flutter code generator for your assets, fonts, colors, … — Get rid of all String-based APIs.
version: 0.0.17
komepage: https://github.com/wasabeef/FlutterGen

environment:
  sdk: '>=2.7.0 <3.0.0'

executables:
  fluttergen: flutter_gen_command

dependencies:
  build: ^1.3.0
  args: ^1.6.0
  path: ^1.7.0
  yaml: ^2.2.1
  mime: ^0.9.7
  xml: ^4.2.0
  dart_style: ^1.3.6

dev_dependencies:
  test:
  pedantic:
  build_test:
